# Generated by Django 2.1.2 on 2018-11-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181108_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='body',
            new_name='AbsoluteLength',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='bag',
            new_name='AvgPressure',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='down',
            new_name='AvgSpeed',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='elb',
            new_name='Duration',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='fox',
            new_name='EndX',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='gaot',
            new_name='EndY',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='horse',
            new_name='StartX',
        ),
        migrations.RemoveField(
            model_name='note',
            name='title',
        ),
        migrations.AddField(
            model_name='note',
            name='Length',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='note',
            name='MoveType',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='note',
            name='StartY',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='note',
            name='UserID',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
    ]
